name: Frontend Deployment
on:
  push:
    branches:
      - master
    paths:
      - "web/**"
jobs:
  build_and_deploy:
    if: github.repository_owner == 'tfkhdyt'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        working-directory: "./web"
        run: |
          docker login --username tfkhdyt --password ${{ secrets.DOCKER_PASS }}
          docker build -t tfkhdyt/gan-an-wo-web:latest --build-arg API_URL=${{ secrets.API_URL }} --build-arg API_SECRET_KEY=${{ secrets.API_SECRET_KEY }} .
          docker push tfkhdyt/gan-an-wo-web:latest

